services:
  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - 4000:4000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - postgres
    links:
      - postgres
      - redis
    networks:
      - mynet
    volumes:
      - /usr/src/app/node_modules
      # - ./:/usr/src/app/

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - notecard-app:/var/lib/postgresql/data
    networks:
      - mynet

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - mynet

volumes:
  notecard-app:
    driver: local

networks:
  mynet:
    driver: bridge
