services:
  frontend:
    restart: always
    container_name: frontend_container
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      SESSION_SECRET: randomizedstringaasdfasdf
      CORS_ORIGIN: http://3.80.194.205:3000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
      - redis
    restart: always
    networks:
      - mynet

  # nginx-proxy:
  #   image: nginx
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - ./www:/var/www:ro
  #     - ./conf.d:/etc/nginx/conf.d:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #     - ./snippets:/etc/nginx/snippets:ro
  #     - ./protect:/etc/nginx/protect:ro
  #   networks:
  #     - mynet

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - notecard-app:/var/lib/postgresql/data
    networks:
      - mynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   networks:
  #     - mynet
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - mynet
    volumes:
      - redis-data:/data

volumes:
  notecard-app:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  mynet:
    driver: bridge
